#ifndef LIBCCAP_BITFIELDS_INCL_C
#define LIBCCAP_BITFIELDS_INCL_C
// Autogenerated by generate_bitfield.py

#if !defined(LIBCCAP_NO_STANDARD_HEADERS)
#include <stdint.h>
#endif

struct Cap2024_11_Bits {
	/** 5-bit field */
	uint8_t encoded_elem_width;
	/** 49-bit field */
	uint64_t b_c;
	/** 4-bit field */
	uint8_t index_size_div;
	/** 15-bit field */
	uint16_t index;
	/** 14-bit field */
	uint16_t range_x;
	/** 14-bit field */
	uint16_t range_y_minus_one;
	/** 23-bit field */
	uint32_t secret_key_id;
	/** 4-bit field */
	uint8_t perms;
};

static struct Cap2024_11_Bits Cap2024_11_Bits_unpack(const uint8_t (*backing)[16]) {
	struct Cap2024_11_Bits value = {0};
	value.encoded_elem_width = (
		(((*backing)[0] >> 0u) & (uint8_t)0x1ful)
	);
	value.b_c = (
		((uint64_t)(((*backing)[0] >> 5u) & (uint8_t)0x7ul) << 0) | 
		((uint64_t)(((*backing)[1] >> 0u) & (uint8_t)0xfful) << 3) | 
		((uint64_t)(((*backing)[2] >> 0u) & (uint8_t)0xfful) << 11) | 
		((uint64_t)(((*backing)[3] >> 0u) & (uint8_t)0xfful) << 19) | 
		((uint64_t)(((*backing)[4] >> 0u) & (uint8_t)0xfful) << 27) | 
		((uint64_t)(((*backing)[5] >> 0u) & (uint8_t)0xfful) << 35) | 
		((uint64_t)(((*backing)[6] >> 0u) & (uint8_t)0x3ful) << 43)
	);
	value.index_size_div = (
		((((*backing)[6] >> 6u) & (uint8_t)0x3ul) << 0) | 
		((((*backing)[7] >> 0u) & (uint8_t)0x3ul) << 2)
	);
	value.index = (
		((uint16_t)(((*backing)[7] >> 2u) & (uint8_t)0x3ful) << 0) | 
		((uint16_t)(((*backing)[8] >> 0u) & (uint8_t)0xfful) << 6) | 
		((uint16_t)(((*backing)[9] >> 0u) & (uint8_t)0x1ul) << 14)
	);
	value.range_x = (
		((uint16_t)(((*backing)[9] >> 1u) & (uint8_t)0x7ful) << 0) | 
		((uint16_t)(((*backing)[10] >> 0u) & (uint8_t)0x7ful) << 7)
	);
	value.range_y_minus_one = (
		((uint16_t)(((*backing)[10] >> 7u) & (uint8_t)0x1ul) << 0) | 
		((uint16_t)(((*backing)[11] >> 0u) & (uint8_t)0xfful) << 1) | 
		((uint16_t)(((*backing)[12] >> 0u) & (uint8_t)0x1ful) << 9)
	);
	value.secret_key_id = (
		((uint32_t)(((*backing)[12] >> 5u) & (uint8_t)0x7ul) << 0) | 
		((uint32_t)(((*backing)[13] >> 0u) & (uint8_t)0xfful) << 3) | 
		((uint32_t)(((*backing)[14] >> 0u) & (uint8_t)0xfful) << 11) | 
		((uint32_t)(((*backing)[15] >> 0u) & (uint8_t)0xful) << 19)
	);
	value.perms = (
		(((*backing)[15] >> 4u) & (uint8_t)0xful)
	);
	return value;
}
static void Cap2024_11_Bits_pack(const struct Cap2024_11_Bits* value, uint8_t (*backing)[16]) {
	(*backing)[0] = (
		(((value->encoded_elem_width >> 0u) & (uint8_t)0x1ful) << 0) | 
		((uint8_t)((value->b_c >> 0u) & 0x7ul) << 5)
	);
	(*backing)[1] = (
		(uint8_t)((value->b_c >> 3u) & 0xfful)
	);
	(*backing)[2] = (
		(uint8_t)((value->b_c >> 11u) & 0xfful)
	);
	(*backing)[3] = (
		(uint8_t)((value->b_c >> 19u) & 0xfful)
	);
	(*backing)[4] = (
		(uint8_t)((value->b_c >> 27u) & 0xfful)
	);
	(*backing)[5] = (
		(uint8_t)((value->b_c >> 35u) & 0xfful)
	);
	(*backing)[6] = (
		((uint8_t)((value->b_c >> 43u) & 0x3ful) << 0) | 
		(((value->index_size_div >> 0u) & (uint8_t)0x3ul) << 6)
	);
	(*backing)[7] = (
		(((value->index_size_div >> 2u) & (uint8_t)0x3ul) << 0) | 
		((uint8_t)((value->index >> 0u) & (uint16_t)0x3ful) << 2)
	);
	(*backing)[8] = (
		(uint8_t)((value->index >> 6u) & (uint16_t)0xfful)
	);
	(*backing)[9] = (
		((uint8_t)((value->index >> 14u) & (uint16_t)0x1ul) << 0) | 
		((uint8_t)((value->range_x >> 0u) & (uint16_t)0x7ful) << 1)
	);
	(*backing)[10] = (
		((uint8_t)((value->range_x >> 7u) & (uint16_t)0x7ful) << 0) | 
		((uint8_t)((value->range_y_minus_one >> 0u) & (uint16_t)0x1ul) << 7)
	);
	(*backing)[11] = (
		(uint8_t)((value->range_y_minus_one >> 1u) & (uint16_t)0xfful)
	);
	(*backing)[12] = (
		((uint8_t)((value->range_y_minus_one >> 9u) & (uint16_t)0x1ful) << 0) | 
		((uint8_t)((value->secret_key_id >> 0u) & 0x7u) << 5)
	);
	(*backing)[13] = (
		(uint8_t)((value->secret_key_id >> 3u) & 0xffu)
	);
	(*backing)[14] = (
		(uint8_t)((value->secret_key_id >> 11u) & 0xffu)
	);
	(*backing)[15] = (
		((uint8_t)((value->secret_key_id >> 19u) & 0xfu) << 0) | 
		(((value->perms >> 0u) & (uint8_t)0xful) << 4)
	);

}

#endif // LIBCCAP_BITFIELDS_INCL_C
