name: Check coding style
on: [pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git --no-pager log --oneline -100
      - run: git show --stat "${{ github.base_ref }}"
      - run: git show --stat "${{ github.sha }}"
      - name: checkpatch.pl
        run: ./scripts/checkpatch.pl --no-signoff --branch "${{ github.base_ref }}..${{ github.sha }}"
      - name: Check clang-format
        uses: wolletd/clang-format-checker@v1
        with:
          target-ref: "${{ github.base_ref }}" # required, merge target
          clang-version: 12     # optional, default: 12
          
